.gitignore
add s.copy.yaml and **/node_modules to .gitignore
=> docs: gitignore update

examples/custom-container-function/Dockerfile, examples/custom-container-function/package.json, examples/custom-container-function/s.yaml, examples/custom-container-function/server.js, src/index.ts, src/lib/fc/function.ts, src/lib/resource/acr.ts, src/lib/resource/client.ts, src/lib/static.ts
1. 更改 pushRegistry 为 push-registry
2. 修复 push-registry 的 bug，对 apiVersion： 2016-06-07  的 acr sdk 进行适配
3.  custom-container 的 handler 支持用户指定
=> Fix push registry bug

src/lib/fc/custom-domain.ts
=> feat: add get domain auto cache

examples/code-local/code/index.js, examples/code-local/s.yaml, readme.md, src/index.ts, src/lib/fc/fc-deploy.ts, src/lib/fc/function.ts, src/lib/fc/service.ts, src/lib/fc/trigger.ts, src/lib/static.ts
delete --use-remote flag; add stateful config to judge if need to ask user about use-remote or
use-local
BREAKING CHANGE: delete --use-remote flag
fix #42
=> perf: upgrade deploy logic

src/index.ts
=> feat: update remove

src/index.ts, src/lib/fc/function.ts, src/lib/static.ts
=> feat: update deploy

examples/code-local/.fcignore, examples/code-local/code/.fcignore, src/lib/fc/function.ts, src/lib/ignore.ts
fix https://github.com/devsapp/fc/issues/128
=> fix: fix ignore problem when build path exists

package.json, src/index.ts
1.  pulumi 模式下，支持 deploy service/function/trigger [--trigger-name]
1.  细粒度资源部署时只会进行相应的资源线上配置的同步操作，不会做多余的线上配置更新操作
=> perf: support deploy service/function/trigger in pulumi mode

package.json, src/lib/fc/function.ts, src/lib/resource/acr.ts, src/lib/utils/docker.ts
issue: https://github.com/devsapp/fc/issues/184
=> perf: push registry if deploy custom container function

Makefile, src/index.ts, src/lib/error.ts, src/lib/fc/function.ts, src/lib/resource/acr.ts, src/lib/utils/prompt.ts, src/lib/utils/utils.ts
1. push image automatically, if failed and the image is under vpc registry, then tag it as public network image and push it; 
2. check if region in image is consistent with region in props; 
3. fix login acr registry error when use sub account, details refer to https://github.com/devsapp/fc/issues/230
=> feat: improvement of deploying custom container function

.eslintrc.js, examples/code-local/s.yaml, examples/code-on-oss/s.yaml, examples/code-sdk/s.yaml, examples/custom-container-function/s.yaml, examples/non-http-trigger/s.yaml, examples/only-service/s.yaml, examples/resource-exists-online/s.yaml, examples/service-with-auto/s.yaml, src/index.ts, src/lib/fc/service.ts, tsconfig.json
set --escape-nas-check to escape ensuring nas directory when put user-defined nasConfig in s.yaml
=> feat: add --escape-nas-check option

readme.md, src/lib/fc/custom-domain.ts, src/lib/fc/fc-deploy.ts, src/lib/static.ts, src/lib/utils/utils.ts
删除完资源之后，将缓存文件也清空掉：https://github.com/devsapp/fc/issues/96
=> feat: clear state cache file

src/lib/fc/trigger.ts
=> fix: deploy trigger error

src/index.ts, src/lib/fc/custom-domain.ts
- 支持 s cli fc remove domain --domain-name
=> feat: support cli domain

src/index.ts, src/lib/resource/nas.ts
=> feat: retry remove nas assist

src/index.ts, src/lib/component/fc-base-sdk/command/deploy.ts, src/lib/component/fc-base-sdk/command/function-async-config.ts
- layers: 如果自定义 endpoint 不在兜底，那么如果要清空 layers 就需要手动配置 layers 为空了
- asyncConfiguration: 处理 asyncConfiguration
=> costom endpint not support layers default array

src/interface/function.ts, src/lib/fc/function.ts, src/lib/static.ts
https://github.com/devsapp/fc/issues/489
=> feat: support custom config

src/index.ts, src/lib/fc/custom-domain.ts
- 支持 https://github.com/devsapp/fc/issues/643
=> feat: add get cert

package.json, src/lib/ignore.ts
=> fix ignore empty dir

src/lib/component/fc-base-sdk/command/deploy.ts
https://github.com/devsapp/fc/issues/803
=> fix: --type code error

package.json, src/lib/fc/function.ts, src/lib/resource/acr.ts
https://github.com/devsapp/fc/issues/816
=> feat: support push aci

src/index.ts, src/lib/fc/fc-deploy.ts, src/lib/fc/function.ts
https://github.com/devsapp/fc/issues/858
=> feat: support check custom container acceleration status

publish.yaml, src/lib/component/fc-base-sdk/command/deploy.ts
Fix https://github.com/devsapp/fc/issues/822
=> fix: update trigger 400

src/lib/resource/sls.ts
Fix: https://github.com/devsapp/fc/issues/874
=> fix: create sls need to locale lower case

src/lib/fc/function.ts
Signed-off-by: wss-git <wssgryx@163.com>
=> refactor: java runtime jar not compress

src/lib/fc/service.ts, src/lib/resource/nas.ts
https://github.com/devsapp/fc/issues/923
=> feat: deploy service support check nas and vpc association
